version: '2'
services:
  core:
    image: nickbreen/core
    build: .
    environment:
      CRON_D_REBOOT: |
        @reboot root echo Hello Reboot!; touch /.reboot | logger --tag hello-reboot
      CRON_D_HELLO: |
        * * * * * root echo Hello World! | logger --tag hello
        */5 * * * * root echo Hello World! | logger --tag hello/5
